Repository 2024-SummerBootcamp-Team/pratice, pull requests merged in 2024-06, with the labels that each got.

#5 하윙
  hi.txt
Labels: documentation

#9 hi
  minseo.txt
Labels: bug

#10 final test
  leeminseo.txt
Labels: good first issue
